-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN     "carbs" DOUBLE PRECISION,
ADD COLUMN     "fats" DOUBLE PRECISION,
ADD COLUMN     "kcalPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "proteins" DOUBLE PRECISION;
